import os

FIELD_W = 70
FIELD_H = 115
GOAL_W = 20
GOAL_DEPTH_CM = 5

MAX_CONNECTIONS_PER_IP     = 5
MAX_MESSAGES_PER_SEC_CAM   = 60
MAX_MESSAGES_PER_SEC_SPECT = 5
MAX_SPECTATORS             = 20

PORT     = int(os.environ.get('PORT', 8080))
WS_PORT  = PORT + 1
CANVAS_W = 450
CANVAS_H = 800